export type PromptTemplate = {
  slug: string;
  title: string;
  useCase: string;
  whenToUse: string;
  promptText: string;
  tips: string[];
  goodOutputLooksLike: string;
  redFlag: string;
};

export type PromptCategory = {
  slug: string;
  name: string;
  icon: string;
  description: string;
  moduleLink: string;
  prompts: PromptTemplate[];
};

// Four categories per day, five prompts per category — 20 prompts per day,
// 60 total. Every prompt is pre-filled with a concrete, ready-to-paste
// example — most reusing the same handful of scenarios already established
// elsewhere in the course (the Checkout Failure case, the CRM Sync Lag
// case, etc.) so nothing new needs to be introduced live. Swap in your own
// team's real incident details once you're comfortable — none of these
// need to be filled in to run as-is.
export const promptCategories: PromptCategory[] = [
  // ═══════════════════════════════════════════ DAY 1 ═══════════════════════════════════════════
  {
    slug: "hypothesis-generation",
    name: "Hypothesis Generation",
    icon: "Lightbulb",
    description:
      "Getting a fast, well-structured first theory from raw incident notes — without letting that first theory become the only theory.",
    moduleLink: "why-ai-changes-rca",
    prompts: [
      {
        slug: "first-hypothesis",
        title: "First-Pass Hypothesis with Forced Alternatives",
        useCase: "Kick off an investigation from raw notes or a ticket thread.",
        whenToUse: "The moment an incident is reported and the team needs somewhere to start looking — not a final answer.",
        promptText:
          "You are helping generate investigation leads, not a final conclusion. Here is the raw incident information: our email notification service stopped sending password-reset emails starting around 3 PM yesterday. Support has logged 40+ tickets since then. No logs have been pulled yet.\n\nGive me exactly 3 possible root-cause hypotheses, ranked by likelihood. For each one:\n1. State the hypothesis in one sentence.\n2. State what specific evidence in the information above supports it.\n3. State one thing we could check right now that would quickly rule it in or out.\nDo not pick a single 'most likely' answer — present all 3 with equal weight and let the evidence decide.",
        tips: ["Insist on 3 hypotheses, never 1 — this is the single biggest lever against anchoring.", "Read the 'what would rule it out' column first — it tells you whether the hypothesis is actually testable.", "Swap in your own team's real incident details once you're comfortable — this example is ready to run as-is."],
        goodOutputLooksLike: "Three distinct hypotheses, each tied to a specific line of evidence already in the notes, each with a concrete next check.",
        redFlag: "All three hypotheses point to the same underlying cause worded differently, or none cite anything specific from the notes.",
      },
      {
        slug: "pattern-across-tickets",
        title: "Pattern Detection Across Past Tickets",
        useCase: "Spot whether a new incident matches a recurring pattern in ticket history.",
        whenToUse: "When an incident feels familiar and you want to know if it's happened before, fast.",
        promptText:
          "Here are summaries of the last 5 tickets related to account access: \"Login button unresponsive on Safari,\" \"Password reset email delayed 20 min,\" \"Two-factor code not arriving,\" \"Account locked after 3 failed attempts,\" \"Reset link expired immediately.\"\n\nA new incident just came in: password-reset emails stopped sending entirely starting 3 PM yesterday, 40+ tickets logged.\n\nDoes this new incident match a pattern in the ticket history? If yes, name the specific past tickets it resembles and what they had in common. If no clear pattern exists, say so directly — do not stretch a weak similarity into a confident pattern.",
        tips: ["Explicitly told the model to say 'no pattern' rather than force one.", "Ask for ticket IDs it's matching against so you can spot-check the comparison."],
        goodOutputLooksLike: "A short, specific list of matching tickets with what they share — or an honest 'no strong match found.'",
        redFlag: "A confident pattern claim with no specific ticket IDs cited.",
      },
      {
        slug: "self-confidence-score",
        title: "Rate the AI's Own Confidence",
        useCase: "Force a hypothesis to come with a calibrated certainty level instead of uniform confidence.",
        whenToUse: "Any time a first-pass hypothesis is about to be repeated in a channel as if it were settled.",
        promptText:
          "Here is what we know so far: our email notification service stopped sending password-reset emails starting around 3 PM yesterday. That's the whole report — no logs yet. On a scale of 1–10, how confident are you in a root cause, and what specifically is missing that would raise that number?",
        tips: ["Watch whether the number actually moves with more evidence in a follow-up, or if it's decorative.", "A model that gives 8/10 on two sentences of information is telling you something about itself, not the incident."],
        goodOutputLooksLike: "A modest score (typically 3–6 on thin evidence) with a specific, checkable list of what's missing.",
        redFlag: "A high confidence score (8+) justified by general reasoning rather than named missing evidence.",
      },
      {
        slug: "blind-spot-check",
        title: "Blind Spot Check",
        useCase: "Surface what the AI wasn't shown before its hypothesis gets treated as complete.",
        whenToUse: "Right after any hypothesis is generated, before it goes any further.",
        promptText:
          "Based on the hypothesis you just gave — that the email service's SMTP relay credentials likely expired — what information were you NOT given that, if it existed and pointed the other way, would most change your answer?",
        tips: ["This question works on any AI-generated claim, not just RCA — keep it in your back pocket generally.", "If the answer is vague ('more data would help'), push once more for a specific data source."],
        goodOutputLooksLike: "A named, specific piece of missing evidence (a metric, a log source, a system) rather than a generic hedge.",
        redFlag: "\"I have enough information\" as an answer — that's the model overstating its own completeness.",
      },
      {
        slug: "consistency-check",
        title: "Test Consistency With a Reworded Question",
        useCase: "Check whether a hypothesis holds up when asked a slightly different way.",
        whenToUse: "When a hypothesis feels important enough to double-check before it's trusted.",
        promptText:
          "I'm going to ask you the same underlying question twice, worded differently, to check consistency. First: given that our email notification service stopped sending password-reset emails starting 3 PM yesterday with 40+ tickets logged and no other symptoms reported, what's the most likely cause? (Answer, then wait.) Second: given the same evidence, what causes can you rule OUT with confidence, and what does that leave?",
        tips: ["Run both parts in the same conversation so it can't 'forget' its first answer.", "A genuinely well-supported hypothesis tends to survive being asked backward; a shaky one often doesn't."],
        goodOutputLooksLike: "The 'ruled out' answer narrows down to roughly the same candidate as the first answer.",
        redFlag: "The two answers point in noticeably different directions — a sign the first answer wasn't as solid as it sounded.",
      },
    ],
  },
  {
    slug: "ai-tool-confidence",
    name: "AI Tool & Confidence Check",
    icon: "Gauge",
    description:
      "Calibrating trust in the tool itself — which AI is built for which job, and how to catch a model's blind spots before they catch you.",
    moduleLink: "why-ai-changes-rca",
    prompts: [
      {
        slug: "ask-about-its-limits",
        title: "Ask the Tool to Name Its Own Limits",
        useCase: "A fast, honest gut-check on what a tool is and isn't built to be trusted for.",
        whenToUse: "Worth running once with your team, live, so everyone hears the answer in the model's own words.",
        promptText: "In two sentences, what kind of tasks should a leader NOT trust you to do alone during an incident investigation, and why?",
        tips: ["Compare the answer across different AI tools if you use more than one — the differences are informative.", "Revisit this occasionally; model behavior changes over time as tools update."],
        goodOutputLooksLike: "Specific mentions of live system access, unverified facts, or reasoning without grounding.",
        redFlag: "A generic \"I can make mistakes, please verify\" disclaimer with nothing incident-specific.",
      },
      {
        slug: "which-tool-fits",
        title: "Which AI Tool Fits This Task?",
        useCase: "A leadership-level sanity check on whether the right category of tool is being used for a task.",
        whenToUse: "When someone mentions using Copilot, Cursor, or a chat assistant for something and you want a fast gut-check.",
        promptText: "I want to summarize six months of ticket history into a trend report for my leadership team. Should this be done with a conversational assistant like Claude/ChatGPT, or a coding assistant like Copilot/Cursor? Explain in one sentence.",
        tips: ["Use this any time a tool choice sounds slightly off — it's faster than debating it from memory.", "The answer should map cleanly onto this course's field guide from Module 1."],
        goodOutputLooksLike: "A clear recommendation with a one-line reason tied to what each tool category is actually built for.",
        redFlag: "\"Either would work\" for a task that clearly needs live code access or clearly doesn't.",
      },
      {
        slug: "force-confidence-score",
        title: "Force a Numeric Confidence Score",
        useCase: "A reusable version of the self-rating trick, for any claim, not just a root cause.",
        whenToUse: "Any time an AI-sourced claim is about to be repeated as fact.",
        promptText: "Rate your confidence in this claim from 1–10, and justify the number in one sentence: \"the root cause is a race condition in the token refresh handler introduced in the March 14 deploy.\"",
        tips: ["Ask this as a completely separate follow-up message, not bundled into the original question.", "A number without a specific justification is worth treating as decoration."],
        goodOutputLooksLike: "A number paired with a concrete reason — evidence present, evidence absent, or assumption made.",
        redFlag: "A high number justified only by how detailed or technical the original claim sounded.",
      },
      {
        slug: "plain-english-translation",
        title: "Ask for the Simplest Explanation of a Technical Claim",
        useCase: "A translation check before repeating a technical claim from an engineer in a leadership conversation.",
        whenToUse: "Any time you're about to relay a technical explanation you didn't fully follow yourself.",
        promptText: "Explain this in one plain-English sentence, as if to someone with no technical background: \"the sync pipeline uses an idempotent retry with exponential backoff, but the dead-letter queue consumer wasn't provisioned with sufficient IOPS to drain the backlog before the next scheduled run.\"",
        tips: ["If the one-sentence version still doesn't make sense to you, that's useful information — ask the engineer directly instead of guessing.", "Good for prepping a two-minute update before a meeting."],
        goodOutputLooksLike: "A single, jargon-free sentence you could say out loud in a meeting with confidence.",
        redFlag: "The 'plain English' version still contains the same jargon as the original.",
      },
      {
        slug: "second-opinion-prompt",
        title: "Get a Second Opinion From the Same Tool",
        useCase: "A cheap way to pressure-test a claim without leaving the conversation.",
        whenToUse: "When a hypothesis feels a little too convenient and you want a quick counter-check.",
        promptText: "Playing devil's advocate against your own previous answer: what's the strongest argument that this conclusion is wrong?",
        tips: ["This works because it explicitly asks the model to argue against itself rather than just re-confirm.", "Use sparingly — for genuinely important claims, not routine ones.", "Run this as a follow-up right after any of the other prompts in this category."],
        goodOutputLooksLike: "A real counter-argument that engages with the specific evidence, not a token disclaimer.",
        redFlag: "\"I don't see any strong argument against this\" — worth a second, more specific push.",
      },
    ],
  },
  {
    slug: "evidence-validation",
    name: "Evidence Validation",
    icon: "ShieldCheck",
    description:
      "Stress-testing a hypothesis someone already believes — the Module 2 questions, turned into a request the AI has to actually answer.",
    moduleLink: "what-good-looks-like",
    prompts: [
      {
        slug: "stress-test-hypothesis",
        title: "Stress-Test an Existing Hypothesis",
        useCase: "Before a hypothesis goes into a postmortem or a customer update, pressure-test it.",
        whenToUse: "Anytime someone — human or AI — has already proposed a root cause and it's about to be written down as fact.",
        promptText:
          "Here is a proposed root cause: \"The payment gateway's SSL certificate expired at 2:14 AM, causing all HTTPS handshakes to the payment processor to fail.\" Here is the available evidence: checkout success rate dropped from 98% to 41% at 02:11 AM and recovered to 96% by 03:05 AM; config change #5521 (\"increase payment timeout threshold\") deployed at 02:09 AM; gateway logs show a spike in \"upstream timeout\" errors — not SSL errors — starting 02:12 AM; the SSL certificate's expiry is confirmed 8 months out via the certificate manager dashboard; rolling back config #5521 at 02:58 AM correlated with recovery within 7 minutes.\n\nDo three things, in order:\n1. List every specific piece of evidence above that directly supports this hypothesis. If there is none, say so.\n2. List any evidence above that contradicts or is inconsistent with this hypothesis.\n3. Describe one test we could run right now that would disprove this hypothesis if it's wrong.\nBe skeptical by default — your job here is to find holes, not to confirm the theory.",
        tips: ["This is the Module 2 three-question framework, encoded directly into the prompt.", "Pay closest attention to step 2 — a hypothesis with zero contradicting evidence is either very solid or wasn't checked hard enough."],
        goodOutputLooksLike: "A genuinely mixed list — supporting and contradicting evidence both present — plus one concrete disproof test.",
        redFlag: "Step 2 comes back empty every single time regardless of the hypothesis.",
      },
      {
        slug: "argue-the-opposite",
        title: "Argue the Opposite Case",
        useCase: "Show how convincing a wrong claim can sound when defended fluently — a fast way to break overconfidence in a room.",
        whenToUse: "When a claim already feels obviously true and the team could use a reminder that fluency isn't proof.",
        promptText: "Argue as persuasively as you can that the SSL certificate expiration IS the root cause of the checkout failure, using only this evidence: checkout success rate dropped from 98% to 41% at 02:11 AM; gateway logs show timeout errors starting 02:12 AM; the outage resolved by 03:05 AM. Do your best even if you think it's actually unlikely.",
        tips: ["Run this on a claim you already know is false — the gap between how convincing it sounds and how wrong it is is the whole lesson.", "Great for live demos; less useful as a routine investigation step."],
        goodOutputLooksLike: "A fluent, confident-sounding argument that nonetheless doesn't survive the Stress-Test prompt above.",
        redFlag: "None — the point of this prompt is that the output will sound convincing regardless.",
      },
      {
        slug: "one-sentence-disproof",
        title: "One-Sentence Disproof Test",
        useCase: "The fastest possible gut-check, short enough to type mid-incident.",
        whenToUse: "When there's no time for the full stress-test but a claim still needs a check.",
        promptText: "In one sentence: what single piece of evidence would immediately disprove the claim that the SSL certificate caused this checkout outage?",
        tips: ["If nobody can name what would disprove a claim, that's itself a red flag independent of whether the claim is true.", "Keep this one memorized — it's the version you can ask out loud in a meeting."],
        goodOutputLooksLike: "A specific, checkable piece of evidence named in one sentence.",
        redFlag: "A vague answer like \"if the data didn't support it\" — that's not a specific test.",
      },
      {
        slug: "compare-two-hypotheses",
        title: "Compare Two Competing Hypotheses",
        useCase: "Lay two rival theories side by side on the same evidence, instead of evaluating them one at a time.",
        whenToUse: "When the team is split between two plausible explanations.",
        promptText: "Here are two competing hypotheses for the same checkout outage: A) Config change #5521, deployed at 02:09 AM, reduced the payment gateway timeout threshold, cutting off legitimate slow transactions early. B) The payment gateway's SSL certificate expired at 2:14 AM, causing HTTPS handshake failures. Here is the evidence: checkout success rate dropped 98% to 41% at 02:11 AM, recovered to 96% by 03:05 AM; gateway logs show \"upstream timeout\" errors, not SSL errors, starting 02:12 AM; certificate confirmed valid for 8 more months; rolling back #5521 at 02:58 AM correlated with recovery. For each one, list the evidence for and against, then state which is better supported and why — or say if it's genuinely too close to call.",
        tips: ["\"Too close to call\" is a legitimate and useful answer — don't discard the prompt if you get it.", "Good for retrospectives where two team members have different theories."],
        goodOutputLooksLike: "A genuinely comparative table-style answer, not two separate unconnected paragraphs.",
        redFlag: "It picks a favorite in the first sentence and works backward to justify it.",
      },
      {
        slug: "anchoring-score",
        title: "Rate How Well-Anchored This Claim Is",
        useCase: "Quantify evidence-anchoring itself as a quick screening step.",
        whenToUse: "As a fast first pass on any RCA write-up before reading it in full.",
        promptText: "On a scale of 1–10, how well is this claim anchored to specific evidence, versus just asserted? \"The login failures were most likely caused by increased load on the authentication servers during a period of high traffic.\" Justify the score by naming what evidence is present or absent.",
        tips: ["This is a scoring wrapper around the Module 2 evidence-anchoring test — useful for scanning several write-ups quickly.", "Low scores (1–4) are the ones worth reading in full before signing off."],
        goodOutputLooksLike: "A score with named specifics — a ticket ID present, a timestamp absent, and so on.",
        redFlag: "A high score justified by the writing being detailed or well-organized rather than sourced.",
      },
    ],
  },
  {
    slug: "observability-queries",
    name: "Observability Query Requests",
    icon: "Search",
    description:
      "Asking for a query in plain language, and getting back a plain-language explanation of what it will actually check — the Module 2B skill.",
    moduleLink: "reading-ai-evidence",
    prompts: [
      {
        slug: "request-query-with-explanation",
        title: "Request a Query, Require a Plain-Language Explanation",
        useCase: "Have an engineer (or yourself, reading over their shoulder) get a query plus a scope check in one step.",
        whenToUse: "Any time a query is being generated to investigate an incident, not just to explore.",
        promptText:
          "Write a Datadog query that searches our API gateway for latency spikes and error-rate anomalies between 09:15 AM and 10:45 AM today.\n\nAfter the query, add a plain-language explanation with exactly three lines: 'Time window: ...', 'Data source: ...', 'Filters applied: ...' — written so someone with no query-language background can check it's asking the right question.",
        tips: ["This is the query-scope habit from Module 2B built into the request itself.", "As a leader, you only ever need to read the three-line plain-language block."],
        goodOutputLooksLike: "A query plus a clean three-line scope summary matching the incident window you actually care about.",
        redFlag: "The three-line summary is missing, vague, or doesn't match the window you asked for.",
      },
      {
        slug: "check-query-scope",
        title: "Sanity-Check an Observability Query's Scope",
        useCase: "Confirm an AI-generated query actually covered the right window, source, and filters.",
        whenToUse: "Any time someone reports 'the query confirmed it' or 'the query found nothing' — before you accept either.",
        promptText: "Here is a query that was run: a search for API errors and anomalies over 'the last 60 minutes,' starting at 11:40 AM. Here is the incident window we care about: 09:15 AM to 10:45 AM, on our API gateway.\n\nExplain, in plain language a non-technical reader can follow, exactly what time window this query covers, what data source or index it searches, and any filters it applies. Then state clearly: does this query's scope actually match the incident window and system stated above, or is there a mismatch?",
        tips: ["Always supply the incident window and system independently — don't let the model infer it from the query.", "This is the single most valuable prompt in this category — memorize the shape of it."],
        goodOutputLooksLike: "A plain-language breakdown of window/source/filters plus an explicit yes/no on the match.",
        redFlag: "A vague \"this query looks reasonable\" answer with no restated time window.",
      },
      {
        slug: "vague-report-to-query",
        title: "Request the Right Query From a Vague Report",
        useCase: "Turn a fuzzy customer complaint into a query request, while surfacing the assumptions being made.",
        whenToUse: "Early in an investigation, when the only input is a vague symptom.",
        promptText: "A customer reported 'things feel slow sometimes' with no other detail. Draft a plain-language description of a query that would help investigate this, and explicitly list every assumption you had to make to write it (time window, system, what 'slow' means).",
        tips: ["The assumptions list is the valuable part — it turns a vague report into a set of specific things to confirm with the customer.", "Use this before, not instead of, asking the customer clarifying questions."],
        goodOutputLooksLike: "A short query description plus an explicit, numbered list of assumptions made.",
        redFlag: "A confident, specific query with no assumptions listed at all — vague input can't produce that honestly.",
      },
      {
        slug: "cross-platform-query",
        title: "Compare the Same Question Across Two Platforms",
        useCase: "See how the same investigative question translates across your team's actual tools.",
        whenToUse: "When your team uses more than one observability platform and needs to know both.",
        promptText: "In plain language, describe how you'd investigate 'error rate spike on the checkout service in the last hour' first using Splunk-style log search, then using Datadog-style metrics dashboards. Keep each description to two sentences.",
        tips: ["Good for onboarding engineers who know one platform but not the other.", "Notice the two descriptions ask different kinds of questions — that's Module 2B's platform distinction in action."],
        goodOutputLooksLike: "Two genuinely different descriptions reflecting each platform's actual strength (log search vs. metrics).",
        redFlag: "Two nearly identical descriptions that just swap the product name.",
      },
      {
        slug: "what-clean-result-proves",
        title: "Ask What a Clean Result Actually Proves",
        useCase: "Stop a 'no anomalies found' result from being over-trusted.",
        whenToUse: "Whenever a query comes back clean and someone's about to conclude the system is fine.",
        promptText: "This query came back with no anomalies: a search of the API gateway for errors over 'the last 60 minutes,' run at 11:40 AM. Given its actual scope, what does this result rule out, and what does it NOT rule out — especially if the customer-reported issue window was actually 09:15 to 10:45 AM?",
        tips: ["This is the single question that would have caught the wrong-time-window trap from the API Latency case study.", "A clean result is only as informative as the query's scope — this prompt makes that explicit."],
        goodOutputLooksLike: "A clear split: what's genuinely ruled out, and what's still an open question given the query's limits.",
        redFlag: "\"This rules out the issue being on our side\" stated without qualifying the query's actual scope.",
      },
    ],
  },

  // ═══════════════════════════════════════════ DAY 2 ═══════════════════════════════════════════
  {
    slug: "team-coaching",
    name: "Team Coaching & Validation",
    icon: "UserCheck",
    description:
      "Practicing the exact language of 'AI proposes, human validates' — validating questions, anti-pattern spotting, and blameless coaching notes.",
    moduleLink: "coaching-your-team",
    prompts: [
      {
        slug: "draft-validating-question",
        title: "Draft a Validating Question for a Rushed Update",
        useCase: "Get 2–3 short validating questions ready before a tense incident-channel moment.",
        whenToUse: "The moment someone is about to post an AI-sourced hypothesis under time pressure.",
        promptText: "Someone is about to post this AI-generated root cause in an incident channel under time pressure: \"the database connection pool is exhausted due to a leak introduced in yesterday's deploy.\" Draft 2–3 short validating questions a leader could ask that wouldn't slow the team down or feel accusatory.",
        tips: ["Keep the questions to one sentence each — anything longer won't get asked live.", "Test these on yourself before a real incident so they're already natural by the time you need them."],
        goodOutputLooksLike: "Short, curious-sounding questions aimed at the evidence, not the person.",
        redFlag: "Questions that sound like an audit (\"prove this is correct\") rather than a quick check.",
      },
      {
        slug: "spot-anti-pattern",
        title: "Spot the Anti-Pattern in This Message",
        useCase: "Train the eye to recognize prompt-and-paste, anchoring, or skipped-validation in the wild.",
        whenToUse: "When reviewing incident channel transcripts or coaching a team member after the fact.",
        promptText: "Here is a message from an incident channel: \"AI says it's the connection pool, going with that, updating the customer now.\" Does it show signs of prompt-and-paste RCA, anchoring on a first answer, or skipping validation under deadline pressure? Name which pattern, if any, and quote the specific phrase that signals it.",
        tips: ["Run this on a real (sanitized) past transcript from your own team for a much stronger coaching conversation than a generic example.", "\"None of these\" is a valid and useful answer too."],
        goodOutputLooksLike: "A specific pattern named with the exact phrase that triggered it, or an honest \"none of these.\"",
        redFlag: "A pattern claimed with no quoted phrase to back it up.",
      },
      {
        slug: "draft-team-norm",
        title: "Draft a Team Norm in One Sentence",
        useCase: "Get a crisp, postable version of 'AI proposes, human validates' for your own team's channel description or wiki.",
        whenToUse: "When rolling out or reinforcing this norm with your team.",
        promptText: "Draft a one-sentence team norm statement for 'AI proposes, human validates' that a support team could pin in their incident channel description. Keep it under 20 words.",
        tips: ["Adapt the wording to your team's own tone before posting it — treat this as a first draft, not a final one.", "Pin it somewhere it'll actually be seen during an incident, not just in a document nobody opens."],
        goodOutputLooksLike: "A short, memorable line that would still make sense to someone new to the team.",
        redFlag: "A sentence so long or formal nobody would actually say it out loud.",
      },
      {
        slug: "roleplay-pushback",
        title: "Role-Play the Pushback",
        useCase: "Practice responding to a defensive reaction to a validating question, before it happens for real.",
        whenToUse: "As practice ahead of time, or to debrief a real interaction that felt tense.",
        promptText: "Play a support engineer who just got asked 'what does the log actually show?' by a leader, under deadline pressure, 20 minutes before a customer call. Respond the way a rushed, slightly defensive person might respond realistically — not the ideal response.",
        tips: ["Ask a follow-up in the same thread: 'now play the leader responding calmly to that' — seeing both sides modeled helps more than either alone.", "This is deliberately the realistic, not the ideal, response — that's where the practice value is."],
        goodOutputLooksLike: "A believably human, slightly prickly response — not a caricature.",
        redFlag: "A response so cooperative it doesn't actually give you anything to practice against.",
      },
      {
        slug: "coaching-note-after-catch",
        title: "Turn a Rejected Hypothesis Into a Coaching Moment",
        useCase: "Draft a blameless, specific coaching note after a wrong AI-sourced hypothesis got caught.",
        whenToUse: "After the fact, when a wrong hypothesis was caught before it did damage and it's worth reinforcing the habit.",
        promptText: "An engineer posted an AI-generated hypothesis blaming a database connection pool leak, but it turned out to be a deploy-related config change instead — caught before it reached a customer. Draft a one-paragraph, blameless coaching note that reinforces the validation habit without singling out the person or the mistake.",
        tips: ["Blameless doesn't mean vague — the note should still be specific enough to be useful.", "Deliver this kind of note promptly, while the moment is still fresh and low-stakes."],
        goodOutputLooksLike: "A note that focuses on the process step that worked (the catch) rather than the person who was wrong.",
        redFlag: "Language that names or implicitly blames the specific engineer rather than the process.",
      },
    ],
  },
  {
    slug: "framework-application",
    name: "Framework Application",
    icon: "Route",
    description:
      "Drafting the structured artifacts behind 5 Whys, Fishbone, Fault Tree, and Kepner-Tregoe from raw notes — the AI-assist points Module 4 describes.",
    moduleLink: "mapping-frameworks",
    prompts: [
      {
        slug: "draft-fishbone",
        title: "Draft a Fishbone Diagram from Raw Notes",
        useCase: "Turn messy incident notes into a structured People/Process/Technology/Environment starting draft.",
        whenToUse: "For a broad first pass, or when comparing multiple recurring incidents for a shared pattern.",
        promptText: "Here are raw notes from an incident: a support-ticket sync queue backed up after a scheduled maintenance window, and the manual re-sync trigger was skipped. This is the third time this has happened in two months — once after a deploy, once after a database failover, always with the same missed manual step, and the pipeline itself never actually errors.\n\nSort every potential contributing factor into four categories: People, Process, Technology, Environment. For each category, list only factors that have some support in the notes above — do not invent factors that aren't mentioned or reasonably implied. If a category has no supported factors, say so instead of forcing an entry.",
        tips: ["The 'don't force an entry' instruction matters — a diagram with something in every box regardless of evidence defeats the purpose.", "Use this as a first draft to react to, not a finished diagram."],
        goodOutputLooksLike: "Some categories with 2–3 entries, others genuinely empty — a lopsided result is often more honest.",
        redFlag: "Every category gets exactly one or two entries regardless of how thin the notes are.",
      },
      {
        slug: "draft-is-is-not",
        title: "Draft an IS / IS-NOT Table for Kepner-Tregoe",
        useCase: "Sharpen a fuzzy problem statement into a structured comparison of what's affected versus what isn't.",
        whenToUse: "When the team can't agree on how big or how narrow an incident actually is.",
        promptText: "Here are the incident notes: EU mobile app users reported checkout errors between 9 and 11 AM; US and desktop users reported nothing during that window.\n\nBuild an IS / IS-NOT table across these dimensions: Region, Platform/Device, Time Window, User Segment. For each dimension, state what IS affected and what IS NOT affected, based only on what's in the notes. If the notes don't say enough to fill in a dimension confidently, write 'not enough data' instead of guessing.",
        tips: ["The IS-NOT column is often more diagnostic than the IS column.", "'Not enough data' is a valid, useful answer."],
        goodOutputLooksLike: "A table with at least one 'not enough data' cell if the notes are genuinely incomplete.",
        redFlag: "Every cell confidently filled in even when the source notes don't support that detail.",
      },
      {
        slug: "run-5-whys",
        title: "Run a 5 Whys Chain From Notes",
        useCase: "Get a fast, structured chain of causation from a single incident's notes.",
        whenToUse: "For a fast-moving incident that looks like one clear chain of causation.",
        promptText: "Using only this incident description: \"a support-ticket sync queue backed up after a scheduled maintenance window; the manual re-sync trigger was skipped,\" ask 'why' five times, each answer building on the last, to find a root cause. After each 'why,' briefly state what evidence (if any) in the description supports that specific answer.",
        tips: ["The 'state what evidence supports it' addition is what keeps this from becoming five confident guesses.", "If an answer at any step has no supporting evidence, that's exactly where a human should stop and validate before continuing."],
        goodOutputLooksLike: "Five connected steps, each with either supporting evidence noted or an honest 'no evidence yet, would need to check.'",
        redFlag: "Five steps that all sound equally confident regardless of whether evidence was actually cited.",
      },
      {
        slug: "fault-tree-likelihood",
        title: "Frame Fault Tree Likelihoods",
        useCase: "Get a starting likelihood framing across multiple contributing factors for a combination-style incident.",
        whenToUse: "For safety-, security-, or compliance-sensitive incidents where more than one thing likely had to go wrong together.",
        promptText: "Here is an incident that seems to have required multiple things going wrong at once: the site went down during a period when a backup job was running (extra database load), it was Monday morning (peak traffic), and one database replica was already offline for unrelated maintenance. For each of these three factors, give a rough likelihood framing (low/medium/high) for how much it contributed, based on the pattern-matching against what's described, and explain your reasoning in one sentence each. State clearly that this is a starting estimate, not a measurement.",
        tips: ["Treat every likelihood word here as a hypothesis to validate, not a number to act on — this module is explicit that the final tree stays human-owned.", "Best used for incidents with real stakes, where the extra structure is worth the time."],
        goodOutputLooksLike: "Distinct reasoning per factor, explicitly labeled as a starting estimate.",
        redFlag: "A single number or percentage stated with false precision, with no reasoning attached.",
      },
      {
        slug: "recommend-framework",
        title: "Recommend a Framework for This Incident",
        useCase: "A fast decision-support check on which framework fits a given incident type.",
        whenToUse: "At the start of an investigation, when it's not obvious which structured approach to reach for.",
        promptText: "In one sentence, which RCA framework — 5 Whys, Fishbone, Fault Tree, or Kepner-Tregoe — fits this incident best, and why: \"a payment outage that required three unrelated systems to fail at the same time\"?",
        tips: ["Compare its answer against this course's own decision guide (in the Frameworks resource) — they should generally agree.", "Useful as a fast first move in a retrospective before committing meeting time to one structure."],
        goodOutputLooksLike: "A framework choice with a one-line reason tied to a specific signal in the incident description (scope confusion, combination of failures, etc).",
        redFlag: "A framework recommendation with no incident-specific reasoning attached.",
      },
    ],
  },
  {
    slug: "timeline-reconstruction",
    name: "Timeline Reconstruction",
    icon: "Clock",
    description:
      "Turning scattered logs, alerts, and messages into a single ordered timeline — the foundation every good RCA and every good retrospective starts from.",
    moduleLink: "leading-retrospective",
    prompts: [
      {
        slug: "unify-timeline",
        title: "Unify Scattered Sources into One Timeline",
        useCase: "Combine logs, alerts, and chat messages into a single chronological view.",
        whenToUse: "Right after an incident, before the retrospective — so the meeting opens with facts, not memory.",
        promptText: "Build a single chronological timeline from these sources. Alert log: paging alert fired 02:11 AM for checkout success-rate drop. Deploy log: config change #5521 shipped 02:09 AM. Incident channel: engineer posts SSL certificate theory at 02:20 AM; rollback of #5521 initiated 02:58 AM. Ticket updates: first customer ticket logged 02:13 AM, ticket volume peaks 02:30 AM.\n\nFor every entry, include: exact timestamp, source (which system it came from), and a one-line plain-language description of what happened. Sort strictly by time. Flag any gaps longer than 10 minutes where nothing was logged, and flag any place where two sources disagree on timing.",
        tips: ["The 'flag disagreements' instruction surfaces exactly where evidence is shaky before the meeting starts.", "Always keep the source column — it lets someone verify any single line in seconds."],
        goodOutputLooksLike: "A clean table: timestamp, source, event — with explicit callouts for gaps and disagreements.",
        redFlag: "A tidy narrative paragraph instead of a sourced, timestamped table.",
      },
      {
        slug: "correlate-deploy",
        title: "Correlate Timeline Against Recent Changes",
        useCase: "Check whether a recent deploy, config change, or feature flag lines up with when things broke.",
        whenToUse: "Early in an investigation, as a fast first correlation check — not as a verdict.",
        promptText: "Here is the incident timeline: checkout success rate dropped from 98% to 41% starting 02:11 AM. Here is the change log for the same period: config change #5521 (\"increase payment timeout threshold\") deployed at 02:09 AM; no other deploys, config changes, or feature flag flips in the prior 24 hours.\n\nList every change that occurred within 30 minutes before the first sign of trouble in the timeline. For each, state only that it is 'temporally correlated' — do not claim it caused the incident. Separately, note if no changes occurred in that window at all.",
        tips: ["Notice the prompt explicitly bans the word 'caused' — correlation in time is not causation.", "A 'no changes in that window' result is itself valuable — it rules out the most common first guess."],
        goodOutputLooksLike: "A list of candidate changes with exact timestamps, explicitly labeled as correlation, not cause.",
        redFlag: "Language like 'X caused the incident' appearing anywhere in the output.",
      },
      {
        slug: "flag-repeating-pattern",
        title: "Flag Repeating Patterns Across Multiple Incidents",
        useCase: "Compare several incidents' timelines side by side to find a shared mechanism.",
        whenToUse: "When the same type of incident keeps recurring and each one has been investigated separately.",
        promptText: "Here are notes from three separate incidents, each previously investigated on its own. Incident 1 (6 weeks ago): sync queue backed up after a scheduled maintenance window; manual re-sync trigger was skipped. Incident 2 (3 weeks ago): sync queue backed up after a deploy; manual re-sync trigger was skipped. Incident 3 (this week): sync queue backed up after a database failover; manual re-sync trigger was skipped. In all three, the sync pipeline itself never logged an error — it silently paused waiting for the trigger.\n\nSort strictly by time within each, then tell me: is there a step, trigger, or mechanism that repeats identically across all three, even though the surface trigger differs each time?",
        tips: ["This is the exact question that catches a recurring process gap that three separate 5 Whys sessions would each miss individually.", "Works best with at least three incidents — patterns are hard to see in just one or two."],
        goodOutputLooksLike: "A named, specific shared mechanism, distinct from each incident's individual trigger event.",
        redFlag: "\"These incidents don't appear related\" without checking for a shared underlying step.",
      },
      {
        slug: "timeline-without-conclusion",
        title: "Build the Timeline Without the Conclusion",
        useCase: "Get pure evidence, explicitly withholding any hypothesis, for an evidence-first retrospective opening.",
        whenToUse: "At the very start of a retrospective, before any hypothesis — including an AI-generated one — gets discussed.",
        promptText: "Build a chronological timeline from these notes: sync queue backed up after a scheduled maintenance window 6 weeks ago; sync queue backed up after a deploy 3 weeks ago; sync queue backed up after a database failover this week; in all three cases the sync pipeline itself never logged an error, it silently paused waiting for a manual re-sync trigger; that manual trigger step is documented only on a wiki page linked from an archived onboarding doc. Evidence only — do not include any conclusions, root causes, or hypotheses, even if one seems obvious. If you're tempted to state a cause, leave it out and just note the fact instead.",
        tips: ["This is the single best way to prevent a retrospective from anchoring on the AI's take before the room has even reviewed the facts.", "Print or screen-share this version first; introduce any hypothesis only afterward."],
        goodOutputLooksLike: "A purely factual timeline with zero causal language, even where a cause seems obvious.",
        redFlag: "A phrase like 'likely due to' or 'this suggests' sneaking into an entry.",
      },
      {
        slug: "identify-gaps",
        title: "Identify Gaps in the Evidence Trail",
        useCase: "Find out what's still missing from the timeline before drawing any conclusions.",
        whenToUse: "After a first timeline draft, before the team commits to a hypothesis.",
        promptText: "Here is a timeline: 02:09 AM — config #5521 deployed. 02:11 AM — checkout success rate begins dropping. 02:20 AM — engineer proposes SSL certificate theory in channel. 02:58 AM — config #5521 rolled back. 03:05 AM — success rate recovers to 96%. List every point where there's an unexplained gap — a jump in time with no logged activity, or a transition between events with no clear connecting evidence.",
        tips: ["Each gap identified here is a candidate action item: 'go find out what happened between X and Y.'", "A timeline with zero gaps flagged on a real incident is worth double-checking — real incidents almost always have some."],
        goodOutputLooksLike: "A specific list of time ranges or transitions with nothing evidencing what happened.",
        redFlag: "\"The timeline looks complete\" on a timeline built from partial log sources.",
      },
    ],
  },
  {
    slug: "retrospective-facilitation",
    name: "Retrospective Facilitation",
    icon: "Workflow",
    description:
      "Structuring the meeting itself — an evidence-first agenda, blameless language, and how to hold two competing hypotheses side by side.",
    moduleLink: "leading-retrospective",
    prompts: [
      {
        slug: "evidence-first-agenda",
        title: "Draft an Evidence-First Retrospective Agenda",
        useCase: "Get a ready-to-use meeting structure that puts evidence review before hypothesis discussion.",
        whenToUse: "Before any retrospective where an AI-generated hypothesis is already circulating.",
        promptText: "Draft a 5-step agenda for a 30-minute incident retrospective that puts evidence review before any hypothesis discussion, for this incident: a support-ticket sync queue has backed up three times in two months, each after a different trigger event, always with the same missed manual re-sync step.",
        tips: ["Check whether hypothesis review comes before or after the evidence steps in the draft — that ordering is the whole point of this module.", "Adapt the time boxes to your own team's typical meeting length."],
        goodOutputLooksLike: "An agenda where evidence/timeline review is explicitly step 1 or 2, and hypothesis discussion comes later.",
        redFlag: "An agenda that opens with 'review the proposed root cause.'",
      },
      {
        slug: "blame-to-evidence",
        title: "Rewrite a Blame Statement Into an Evidence Statement",
        useCase: "Keep a retrospective blameless without losing the evidence standard.",
        whenToUse: "When a note or comment drifts toward blaming a person instead of examining a process.",
        promptText: "Rewrite this in a blameless tone without losing the evidence standard: \"someone should have caught that the retry logic was broken before this shipped.\"",
        tips: ["A good rewrite usually shifts the subject from a person to a process or a gap.", "Use this live, in the moment, when a retrospective starts to drift toward blame."],
        goodOutputLooksLike: "A rewritten sentence focused on the process gap, still specific enough to be useful.",
        redFlag: "A vague, watered-down rewrite that loses the specific, useful detail along with the blame.",
      },
      {
        slug: "constructive-challenge-questions",
        title: "Draft Questions to Challenge a Hypothesis Constructively",
        useCase: "Get curious, non-accusatory questions ready for challenging an AI-suggested cause.",
        whenToUse: "When an AI-generated hypothesis needs to be examined without dismissing it outright.",
        promptText: "Draft 3 questions a retrospective facilitator could ask to constructively challenge this AI-suggested root cause, without dismissing it outright: \"a transient network issue during the maintenance window caused the sync failure.\"",
        tips: ["These should sound like genuine curiosity, not cross-examination — read them aloud to check the tone before using them.", "Works well as a fallback if the room goes quiet after a hypothesis is presented."],
        goodOutputLooksLike: "Three specific, evidence-aimed questions that don't presuppose the hypothesis is wrong.",
        redFlag: "Questions that could just as easily be read as an attack on whoever proposed the hypothesis.",
      },
      {
        slug: "summarize-disagreement",
        title: "Summarize Disagreement Between Two Hypotheses",
        useCase: "Lay out a genuine disagreement for the room instead of letting it stay implicit.",
        whenToUse: "When the AI's hypothesis and the team's instinct conflict and both deserve consideration.",
        promptText: "Here are two theories for the same incident. AI-generated: \"a transient network issue during the maintenance window caused this sync failure — an isolated, one-off event.\" Team's instinct: \"this is the third time this exact failure mode has happened, so it's probably a recurring process gap, not a network blip.\" Lay both out side by side with the evidence each one has, neutrally, without picking a winner.",
        tips: ["Explicitly ask it not to pick a winner — that decision belongs to the room, not the model.", "Great for a shared screen during the actual retrospective."],
        goodOutputLooksLike: "A balanced, side-by-side comparison that leaves the actual decision open.",
        redFlag: "A conclusion or recommendation appearing despite being asked not to pick a winner.",
      },
      {
        slug: "open-questions-section",
        title: "Draft the 'What We Still Don't Know' Section",
        useCase: "Give a postmortem an honest, explicit list of open questions instead of forcing a premature conclusion.",
        whenToUse: "When the evidence doesn't yet support a fully confident root cause but a postmortem still needs to go out.",
        promptText: "Based on this timeline and discussion: the sync pipeline has failed three times after three different trigger events, always via the same missed manual re-sync step, and the step itself is only documented on an archived wiki page — draft a 'What We Still Don't Know' section for a postmortem — a short list of specific open questions, not vague uncertainty.",
        tips: ["This section is often the most honest part of a postmortem — don't skip it under pressure to look conclusive.", "Each open question here becomes a natural action item for follow-up investigation."],
        goodOutputLooksLike: "A short list of specific, answerable questions rather than a general disclaimer.",
        redFlag: "A single vague line like 'more investigation may be needed' with nothing specific named.",
      },
    ],
  },

  // ═══════════════════════════════════════════ DAY 3 ═══════════════════════════════════════════
  {
    slug: "stakeholder-communication",
    name: "Stakeholder Communication",
    icon: "Megaphone",
    description:
      "Translating a technical finding into the right update for the right audience — and catching overpromises before they ship.",
    moduleLink: "incident-communication",
    prompts: [
      {
        slug: "executive-summary",
        title: "Executive Summary from Technical Notes",
        useCase: "Translate an engineering-facing incident summary into a 3-sentence executive update.",
        whenToUse: "Whenever a technical write-up needs to go to a non-technical stakeholder fast.",
        promptText: "Here is a technical incident summary written for engineers: checkout success rate dropped from 98% to 41% for 54 minutes due to config change #5521 reducing the payment gateway timeout threshold; the change was rolled back and success rate recovered to 96% within 7 minutes; full confirmation of root cause is complete.\n\nRewrite this as a 3-sentence update for an executive with no technical background. Sentence 1: what happened and who was affected, in business terms. Sentence 2: current status, stated with the same confidence level the technical summary actually has — do not round 'likely resolved' up to 'resolved.' Sentence 3: what happens next and when the next update will come.",
        tips: ["The 'don't round up confidence' instruction is the highest-value line — it's where overpromising sneaks in.", "Always compare the confidence words in the output against what the team has actually confirmed."],
        goodOutputLooksLike: "Three tight sentences with hedging language that matches — not exceeds — the team's actual confidence.",
        redFlag: "The word 'resolved' or 'fixed' appearing when the source only said 'likely' or 'appears to.'",
      },
      {
        slug: "customer-update",
        title: "Customer-Facing Update with Liability Check",
        useCase: "Draft a customer notification that doesn't overpromise a cause or admit fault prematurely.",
        whenToUse: "For any customer-facing update during or after an active incident.",
        promptText: "Draft a customer-facing status update based on this internal summary: checkout failures affected roughly 60% of transactions for about an hour; the team believes a recent configuration change caused it and has since rolled that change back; success rates have returned to normal but full confirmation is still in progress.\n\nRequirements: state the customer-visible impact clearly and first. Do not name an internal root cause unless it has been fully confirmed. Do not use language that could be read as admitting fault or liability unless that has been explicitly approved. Keep it under 100 words. After the draft, list separately any sentence you were unsure about from a liability or overpromising standpoint.",
        tips: ["The self-flagging list is worth the extra line — it surfaces exactly what needs your review pass.", "Never send this draft without a human reading the self-flagged list first."],
        goodOutputLooksLike: "A concise, impact-first update with cautious cause language, plus a short self-flagged list.",
        redFlag: "A specific named root cause in a customer-facing draft when the internal summary only described a theory.",
      },
      {
        slug: "confidence-tiered-versions",
        title: "Match Hedging Language to Actual Confidence",
        useCase: "Get three versions of the same update at different confidence levels, so you can pick the one that's actually true.",
        whenToUse: "When you're not sure how confident to sound and want the options laid out explicitly.",
        promptText: "Here is a technical status: checkout failures traced to config change #5521; change rolled back; success rate recovered. Draft three one-sentence versions of a stakeholder update: one assuming the cause is fully confirmed, one assuming it's a likely-but-unconfirmed theory, and one assuming it's still under active investigation. Label each clearly.",
        tips: ["Pick the version that matches your team's actual confidence — don't default to the most reassuring one.", "Useful for training new leads on how much hedging language actually changes a sentence."],
        goodOutputLooksLike: "Three genuinely distinct sentences, not the same sentence with a word or two swapped.",
        redFlag: "All three versions sound nearly identical in confidence despite being labeled differently.",
      },
      {
        slug: "two-audiences-at-once",
        title: "Translate a Technical Update for Two Audiences at Once",
        useCase: "Produce the executive and customer versions of the same update side by side, to compare tone and content differences.",
        whenToUse: "When both updates need to go out around the same time and consistency matters.",
        promptText: "Here is a technical incident summary: checkout failures affected roughly 60% of transactions for about an hour due to a configuration change, which has been rolled back; success rates have returned to normal. Produce two versions: one for an internal executive audience (business impact, status, next steps), one for external customers (impact, cautious cause language, reassurance without overpromising). Keep both under 80 words each.",
        tips: ["Read both versions side by side before sending either — they should tell a consistent story with different framing, not different facts.", "A mismatch between the two versions is worth catching before either goes out."],
        goodOutputLooksLike: "Two versions with consistent facts, appropriately different tone and detail level for each audience.",
        redFlag: "The customer version implies more certainty about the cause than the executive version does.",
      },
      {
        slug: "self-flag-riskiest-line",
        title: "Self-Flag the Riskiest Line",
        useCase: "Get the draft to point out its own weakest spot before you have to find it yourself.",
        whenToUse: "As a final pass on any draft heading to a customer or executive audience.",
        promptText: "Here is a draft update: \"We have identified and resolved the root cause of the checkout issue, which was caused by an error in our payment processing configuration.\" Which single sentence in this draft carries the most liability or overpromising risk, and why? Suggest a safer rewrite of just that sentence.",
        tips: ["This is a fast final check — 30 seconds, one sentence in, one sentence out.", "If the flagged sentence surprises you, that's exactly the value of running this check."],
        goodOutputLooksLike: "One specific sentence quoted, with a clear reason and a concrete safer rewrite.",
        redFlag: "\"The draft looks fine as written\" on a draft that names an unconfirmed cause.",
      },
    ],
  },
  {
    slug: "data-sanitization",
    name: "Data Sanitization",
    icon: "ShieldAlert",
    description:
      "A second set of eyes for what needs redacting before anything reaches an AI tool — the Module 6 data-handling guardrail, as a repeatable request.",
    moduleLink: "governance-risk-privacy",
    prompts: [
      {
        slug: "flag-redactions",
        title: "Flag What Needs Redacting Before It Goes Anywhere",
        useCase: "Get a second set of eyes on a log snippet or ticket thread before it's pasted into any AI tool.",
        whenToUse: "Every time, before production logs or customer data reach an AI tool — run this in your organization's approved tool only.",
        promptText: "Review this text and list every piece of information that looks like it could be PII, a credential, or a token — names, emails, account IDs, session tokens, API keys, IP addresses, phone numbers, or anything else that could identify a specific person or grant access to a system: \"Customer jane.doe@example.com (acct #88213) reported the issue at 09:41. Pulled logs from host prod-api-07, session token eyJhbGciOiJIUzI1NiJ9.mock, source IP 203.0.113.44. Escalated to on-call via internal Slack, cc'd manager rgupta@example.com.\"\n\nFor each item found, quote the exact snippet and say what category it falls into. Do not summarize or analyze the incident itself — this pass is only for finding what needs to be redacted before the real analysis happens.",
        tips: ["Run this as its own separate step, before the actual RCA analysis prompt.", "Treat this as a second check, not a replacement for your team's existing sanitization process."],
        goodOutputLooksLike: "A short, specific list of exact snippets flagged with categories.",
        redFlag: "A vague 'this looks fine, no sensitive data found' with no itemized list.",
      },
      {
        slug: "safe-to-paste-check",
        title: "Check If a Log Snippet Is Safe to Paste",
        useCase: "A fast yes/no gut-check before pasting a specific snippet anywhere.",
        whenToUse: "When you're not sure whether a specific piece of text needs sanitizing first.",
        promptText: "Is this text safe to paste into an external AI tool as-is, or does it need redaction first? Answer yes or no, then explain in one sentence: \"Checkout errors spiked at 02:11 AM on host prod-api-07, correlating with config change #5521.\"",
        tips: ["When in doubt, this prompt should still be run inside your organization's approved tool, not a consumer-grade one — the check itself is sensitive if the data is.", "A 'no' answer should always be followed by the Flag What Needs Redacting prompt above."],
        goodOutputLooksLike: "A clear yes/no with a one-sentence reason naming what's present or confirmed absent.",
        redFlag: "\"Probably fine\" as an answer — this needs to be a clear yes or no.",
      },
      {
        slug: "draft-redacted-version",
        title: "Draft a Redacted Version",
        useCase: "Get a usable, redacted version of a snippet, not just a list of what to remove.",
        whenToUse: "After running the redaction-flagging check, when you need the cleaned text itself.",
        promptText: "Here is a log snippet with sensitive information: \"Customer jane.doe@example.com (acct #88213) reported the issue at 09:41. Pulled logs from host prod-api-07, session token eyJhbGciOiJIUzI1NiJ9.mock, source IP 203.0.113.44. Escalated to on-call via internal Slack, cc'd manager rgupta@example.com.\" Produce a redacted version with each piece of PII, credential, or token replaced with a clear placeholder like [EMAIL] or [TOKEN], preserving everything else exactly as written.",
        tips: ["Spot-check the redacted version against the original before using it — placeholder substitution can occasionally miss an item.", "This is the version that's actually safe to paste elsewhere, not the flagged list from the earlier prompt."],
        goodOutputLooksLike: "A version that reads naturally with clear placeholders, and nothing sensitive slipping through.",
        redFlag: "A redacted version that's missing an item the flagging prompt caught earlier — always cross-check the two.",
      },
      {
        slug: "why-approved-tool-matters",
        title: "Explain Why an Approved Tool Matters for This Data",
        useCase: "Get a ready-made talking point for explaining tool policy to your team.",
        whenToUse: "When you need to explain, in your own words, why the same task is safe in one tool and not another.",
        promptText: "In two sentences, explain to a non-technical audience why pasting customer account logs into an approved enterprise AI tool is different from pasting them into a free consumer AI account, even if the underlying model is similar.",
        tips: ["Use this to prep a two-minute explanation before a team meeting, not as a policy document itself.", "Confirm the specifics against your own organization's actual approved-tool policy — this prompt gives you the talking point, not the policy."],
        goodOutputLooksLike: "A plain-language explanation centered on data contracts and retention, not technical model differences.",
        redFlag: "An explanation that focuses on model quality rather than data-handling agreements.",
      },
      {
        slug: "draft-reminder-message",
        title: "Draft a One-Line Data-Handling Reminder",
        useCase: "Get a short, postable reminder message for a team channel.",
        whenToUse: "As a periodic nudge, or right after a near-miss involving sensitive data.",
        promptText: "Draft a short, friendly Slack-style reminder message (under 30 words) reminding a support team not to paste production customer data into consumer-grade AI tools, without sounding like a scolding.",
        tips: ["Post this kind of reminder periodically, not just after something goes wrong — routine reminders normalize the habit.", "Pair it with a link to your team's actual approved-tool list."],
        goodOutputLooksLike: "A short, warm, specific reminder that would actually get read in a busy channel.",
        redFlag: "A message so long or formal it reads like a policy excerpt rather than a reminder.",
      },
    ],
  },
  {
    slug: "governance-trust-calibration",
    name: "Governance & Trust Calibration",
    icon: "BadgeCheck",
    description:
      "Running the trust-calibration checklist and escalation-trigger decisions as live requests — the Module 6 judgment calls, made repeatable.",
    moduleLink: "governance-risk-privacy",
    prompts: [
      {
        slug: "run-trust-checklist",
        title: "Run the Trust-Calibration Checklist Against a Claim",
        useCase: "Get a structured self-check across all three trust-calibration dimensions in one pass.",
        whenToUse: "Before accepting any AI-generated output as a root cause, especially for a higher-stakes incident.",
        promptText: "Here is a proposed root cause: \"The payment gateway's SSL certificate expired at 2:14 AM, causing all HTTPS handshakes to the payment processor to fail.\" Here is the evidence: checkout success rate dropped 98% to 41% at 02:11 AM; gateway logs show upstream timeout errors, not SSL errors; certificate confirmed valid for 8 more months.\n\nScore it against three checks: 1) Source-grounding — does the claim trace to specific evidence? 2) Alternative-hypothesis — were other explanations genuinely considered? 3) Blast-radius — if this is wrong and we act on it, what does it cost us? Answer each separately.",
        tips: ["This is the full Module 6 checklist as one request — use it for anything above routine severity.", "Read the blast-radius answer first — it tells you how much scrutiny the other two deserve."],
        goodOutputLooksLike: "Three distinct, specific answers rather than one blended paragraph.",
        redFlag: "A single overall 'this seems trustworthy' verdict without addressing the three checks separately.",
      },
      {
        slug: "needs-escalation-check",
        title: "Decide If This Needs Escalation",
        useCase: "A fast check on whether an incident category requires named human sign-off before an AI-assisted conclusion is used.",
        whenToUse: "Early in any incident that might touch security, compliance, or a low-evidence high-stakes scenario.",
        promptText: "In one sentence, does this incident need named human sign-off before an AI-assisted conclusion is finalized, and why: \"unusual login patterns detected on 40 customer accounts overnight, pattern unclear\"?",
        tips: ["This should trip immediately for anything security-adjacent — treat a 'no' answer on something that feels sensitive as worth a second look, not a final word.", "Use this as a fast triage step, not a replacement for your actual escalation policy."],
        goodOutputLooksLike: "A clear yes/no with a reason naming the specific risk category (security, compliance, low-evidence/high-stakes).",
        redFlag: "A confident 'no' on an incident that clearly touches customer security or compliance.",
      },
      {
        slug: "draft-policy-addendum",
        title: "Draft a One-Paragraph Policy Addendum",
        useCase: "Add a lightweight AI sign-off requirement to an existing incident policy without inventing a new process.",
        whenToUse: "When formalizing governance for your team without a full policy rewrite.",
        promptText: "Draft one paragraph to add to an existing incident response policy that requires human sign-off before AI-assisted root causes are finalized for security incidents, without creating a new approval workflow.",
        tips: ["If the draft is more than one paragraph or invents a new process, that's a useful signal — even AI defaults toward adding process instead of staying lightweight.", "Read it aloud to check it actually fits as an addendum, not a replacement policy."],
        goodOutputLooksLike: "A single, tight paragraph that references the existing process rather than replacing it.",
        redFlag: "A multi-section policy document when a single paragraph was requested.",
      },
      {
        slug: "estimate-blast-radius",
        title: "Estimate the Blast Radius of Being Wrong",
        useCase: "Get a concrete cost estimate if a hypothesis is acted on and turns out wrong.",
        whenToUse: "As part of the trust-calibration pass, especially for anything customer-facing.",
        promptText: "If this hypothesis is wrong and we act on it anyway, what's the realistic cost — in time, trust, or compliance exposure: naming the SSL certificate as the confirmed root cause of a checkout outage in a customer-facing postmortem, when the real cause was a config change?",
        tips: ["A concrete, specific cost estimate is far more useful for calibrating scrutiny than a vague 'this could be risky.'", "Compare the estimate against how much time you're about to spend validating — that's the actual trade-off this check is for."],
        goodOutputLooksLike: "A specific, scenario-based cost estimate tied to where the hypothesis would actually be used.",
        redFlag: "A generic 'being wrong is always costly' answer with nothing tied to this specific scenario.",
      },
      {
        slug: "list-signoff-triggers",
        title: "List the Sign-Off Triggers for This Incident Type",
        useCase: "Propose specific escalation triggers for a recurring incident category, ahead of time.",
        whenToUse: "When defining escalation rules in advance, so nobody has to invent them live under pressure.",
        promptText: "For incidents involving unusual customer account access patterns, propose 2–3 specific conditions that should trigger mandatory human sign-off before an AI-assisted conclusion is treated as final.",
        tips: ["Define these triggers during a calm moment, then just reference them during a real incident — that's the entire point of setting them in advance.", "Keep the triggers concrete and checkable, not vague judgment calls."],
        goodOutputLooksLike: "Specific, checkable conditions (a severity level, a data type, a customer tier) rather than vague judgment calls.",
        redFlag: "A trigger like 'when it seems serious' that still requires a judgment call in the moment.",
      },
    ],
  },
  {
    slug: "rca-documentation",
    name: "RCA Documentation",
    icon: "FileText",
    description:
      "Turning a validated investigation into a clean, evidence-anchored write-up — fast, without smoothing over the parts that still need scrutiny.",
    moduleLink: "playbook-prompt-library",
    prompts: [
      {
        slug: "draft-postmortem",
        title: "Draft a Postmortem from Validated Findings",
        useCase: "Produce a first-draft postmortem document once the investigation is actually done.",
        whenToUse: "After validation, not before — this prompt is for writing up a confirmed finding, not for generating one.",
        promptText: "Draft a postmortem using this validated timeline and confirmed root cause: config change #5521, deployed 02:09 AM, reduced the payment gateway timeout threshold, cutting off legitimate slow transactions and logging them as \"upstream timeout.\" Checkout success rate dropped from 98% to 41% starting 02:11 AM. Rolling back #5521 at 02:58 AM correlated with recovery to 96% by 03:05 AM. SSL certificate was checked and ruled out — confirmed valid for 8 more months.\n\nUse this structure: Summary (2-3 sentences), Impact, Timeline (timestamped), Root Cause (with evidence cited inline, not just asserted), What Went Well, What Didn't, Action Items (owner + due date). For the Root Cause section: every claim must reference the evidence provided — do not add any detail that wasn't in the source material.",
        tips: ["The 'do not add detail that wasn't in the source material' instruction stops the model from filling narrative gaps with invention.", "Always read the Root Cause section against the original evidence before this goes near a customer or executive."],
        goodOutputLooksLike: "Every sentence in the Root Cause section maps back to something you actually pasted in.",
        redFlag: "A root cause section with more specific detail than the source material contained.",
      },
      {
        slug: "ai-involvement-note",
        title: "Generate the AI-Involvement Documentation Line",
        useCase: "Standardize how AI involvement gets noted in every postmortem, per your playbook.",
        whenToUse: "As the last step before a postmortem is finalized.",
        promptText: "Based on this investigation summary: \"AI drafted the first hypothesis from ticket history, a human validated it against server logs before the postmortem, and AI drafted this postmortem document from the validated findings,\" write one sentence for the postmortem that documents where AI was used and what was independently validated by a human. Keep it factual and specific — no marketing language, no vague 'AI-assisted' phrasing.",
        tips: ["One sentence is the target length — this is a transparency habit, not a section of the report.", "Specific beats vague: name exactly what was AI-drafted versus human-validated."],
        goodOutputLooksLike: "A single, specific sentence naming what AI did and what a human checked.",
        redFlag: "Generic phrasing like 'AI tools assisted with this analysis.'",
      },
      {
        slug: "draft-full-playbook-entry",
        title: "Draft the Full Three-Line Playbook Entry",
        useCase: "Get all three playbook lines drafted at once for a given recurring incident type.",
        whenToUse: "When starting a team's AI-RCA playbook from scratch.",
        promptText: "Draft a three-line playbook entry for \"password reset failures\": when AI is used, what sign-off is required, how AI involvement gets documented. Keep each line to one sentence.",
        tips: ["Read the sign-off line specifically and ask: could a tired on-call engineer actually follow this at 2 AM, or does it just sound good?", "Treat this as a first draft to edit against your team's real process, not a final policy."],
        goodOutputLooksLike: "Three genuinely actionable one-sentence lines, not three restatements of the same idea.",
        redFlag: "A sign-off line so vague ('use good judgment') that it couldn't actually be followed or checked.",
      },
      {
        slug: "propose-metrics",
        title: "Propose Metrics Worth Reporting Upward",
        useCase: "Get metric suggestions for demonstrating whether AI-assisted RCA is actually working.",
        whenToUse: "When preparing to report on AI-assisted RCA adoption to your own leadership.",
        promptText: "In one sentence each, name two metrics a team could track to show whether AI-assisted RCA is actually working, beyond just 'we use AI now.'",
        tips: ["Compare its answer against time-to-hypothesis and hypothesis-accuracy-rate — if it lands close, that's confirmation those are the right metrics.", "Pick metrics your team can actually measure today, not ones requiring new tooling."],
        goodOutputLooksLike: "Two specific, measurable metrics rather than vague goals like 'improve efficiency.'",
        redFlag: "A metric like 'AI usage rate' that measures adoption instead of quality or outcome.",
      },
      {
        slug: "adapt-template-to-team",
        title: "Adapt a Prompt Template to Your Team's Fields",
        useCase: "Reword a template's placeholders to match your own ticketing system, without losing what makes it reliable.",
        whenToUse: "When rolling out a prompt template from this library to your own team.",
        promptText: "Here is a prompt template: \"You are helping generate investigation leads, not a final conclusion. Here is the raw incident information: [notes]. Give me exactly 3 possible root-cause hypotheses, ranked by likelihood, each with supporting evidence and one thing to check.\" Rewrite it to use our team's field names: Severity, Component, Reporter, Ticket Summary. Keep every instruction that forces evidence-citing or considering alternatives exactly as-is — only change the field names and examples.",
        tips: ["This is a meta-prompt — use it once per template you plan to standardize on, not for every individual use.", "Double-check that the evidence-citing instructions survived the rewrite unchanged — that's the part doing the real work."],
        goodOutputLooksLike: "The same structural instructions, just with your team's terminology substituted in.",
        redFlag: "The rewrite quietly drops or softens the evidence-citing or alternative-consideration instructions.",
      },
    ],
  },
];

export function getAllPrompts(): (PromptTemplate & { category: string; categorySlug: string })[] {
  return promptCategories.flatMap((cat) =>
    cat.prompts.map((p) => ({ ...p, category: cat.name, categorySlug: cat.slug }))
  );
}
